app:
  port: 9933
  address: "127.0.0.1"
  name: "Supranim Application"
  key: ""
  threads: 1
  assets:
    source: "./assets"
    public: "assets"
  views: "views"

database:
  main:
    driver: "pgsql"
    port: 5432
    host: "localhost"
    prefix: "my_"
    name: "app_sample"
    user: "username"
    password: "postgres"